// Widget tests for the Residential Management app.
//
// Note: The default smoke test generated by `flutter create` was removed
// because our app requires Firebase initialization in main(), which cannot
// be performed in a unit test environment without additional mocking.
//
// Proper widget and integration tests will be added in Sprint 2 once the
// AuthService and UserRepository are in place. For now, this file exists
// as a placeholder so `flutter test` and `flutter analyze` don't complain.

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('placeholder test — real tests coming in Sprint 2', () {
    expect(1 + 1, equals(2));
  });
}