import 'dart:convert';
import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';

import '../features/visitor/domain/visitor_invitation.dart';

/// Thrown when a visitor-pass operation violates a domain invariant
/// (cancelling someone else's pass, cancelling a non-active pass, …). These
/// represent bugs or attacks, not ordinary user-facing errors — mirrors
/// [UserRepositoryException].
class VisitorRepositoryException implements Exception {
  final String message;
  const VisitorRepositoryException(this.message);

  @override
  String toString() => message;
}

/// The single chokepoint for all reads and writes to /visitor_invitations/{token}.
///
/// THREAT MODEL NOTE (read before adding methods):
///   This repository is a CONVENIENCE API over Firestore, not a security
///   boundary. Authorization is enforced SERVER-SIDE by firestore.rules:
///     • create — only a VERIFIED resident (their /users doc says
///       role=resident, status=active, unitNumber set), issuing for THEMSELVES
///       (residentId == auth.uid) and THEIR verified unit (unitNumber pinned to
///       the profile), with a server-stamped createdAt.
///     • the capability token (= doc id) is generated by a CSPRNG here so it is
///       unguessable (CWE-330/CWE-338); the rules never have to trust the
///       client for that.
///   "Security is server-enforced, not client-enforced" — every check this
///   class makes is mirrored by, and subordinate to, the rule.
class VisitorRepository {
  final FirebaseFirestore _firestore;
  final Random _random;

  VisitorRepository({FirebaseFirestore? firestore, Random? random})
    : _firestore = firestore ?? FirebaseFirestore.instance,
      // Random.secure() is a CSPRNG. Injectable ONLY so a test can pin the
      // stream of bytes; production always uses the secure default.
      _random = random ?? Random.secure();

  static const String _collection = 'visitor_invitations';
  static const String qrPayloadPrefix = 'srm-visitor:';

  CollectionReference<Map<String, dynamic>> get _ref =>
      _firestore.collection(_collection);

  // ═══════════════════════════════════════════════════════════════
  // TOKEN
  // ═══════════════════════════════════════════════════════════════

  /// 192 bits of CSPRNG entropy → base64url (no padding) → 32 URL-safe chars.
  ///
  /// This value IS the capability token AND the Firestore document id (see
  /// [VisitorInvitation]): the guard scanner resolves a scanned token with one
  /// keyed `get()`, so no list/query permission is ever required and the id
  /// space is far too large to enumerate (CWE-330/CWE-338, CWE-639).
  String _generateToken() {
    final bytes = List<int>.generate(24, (_) => _random.nextInt(256));
    return base64UrlEncode(bytes).replaceAll('=', '');
  }

  String tokenFromQrPayload(String payload) {
    final trimmed = payload.trim();
    if (!trimmed.startsWith(qrPayloadPrefix)) {
      throw const VisitorRepositoryException(
        'This is not a Residential Hub visitor QR code.',
      );
    }

    final token = trimmed.substring(qrPayloadPrefix.length).trim();
    final tokenRegExp = RegExp(r'^[A-Za-z0-9_-]{16,}$');
    if (!tokenRegExp.hasMatch(token)) {
      throw const VisitorRepositoryException('Visitor QR code is invalid.');
    }
    return token;
  }

  // ═══════════════════════════════════════════════════════════════
  // CREATE
  // ═══════════════════════════════════════════════════════════════

  /// Issues a new active visitor pass and returns the persisted invitation
  /// (with its token populated as [VisitorInvitation.invitationId]).
  ///
  /// `createdAt` is stamped with [FieldValue.serverTimestamp] so the issue time
  /// is server-authoritative, never the forgeable client clock. `unitNumber`
  /// MUST be the caller's VERIFIED unit — the rule pins it to the profile's
  /// `unitNumber`, so passing any other value is rejected server-side.
  Future<VisitorInvitation> createInvitation({
    required String residentId,
    required String unitNumber,
    required String visitorName,
    required String visitorContact,
    int guestCount = 1,
    required String vehiclePlate,
    required DateTime visitDate,
    required String eta,
  }) async {
    if (guestCount < 1 || guestCount > 20) {
      throw const VisitorRepositoryException(
        'Visitor count must be between 1 and 20.',
      );
    }

    final token = _generateToken();

    // The pass is valid through the END of the visit day (local time). This is
    // a hard backstop honoured by VisitorInvitation.isCurrentlyValid regardless
    // of the stored status, and the rule rejects an expiresAt already in the
    // past (expiresAt > request.time).
    final expiresAt = DateTime(
      visitDate.year,
      visitDate.month,
      visitDate.day,
      23,
      59,
      59,
    );

    final plate = vehiclePlate.trim();
    if (plate.isEmpty) {
      throw const VisitorRepositoryException('Vehicle plate is required.');
    }
    final invitation = VisitorInvitation(
      invitationId: token,
      residentId: residentId,
      unitNumber: unitNumber,
      visitorName: visitorName.trim(),
      visitorContact: visitorContact.trim(),
      guestCount: guestCount,
      vehiclePlate: plate,
      visitDate: visitDate,
      eta: eta.trim(),
      status: VisitorPassStatus.active,
      createdAt: DateTime.now(), // placeholder; overwritten by serverTimestamp
      expiresAt: expiresAt,
    );

    // Reuse the model's serialization, then override createdAt with the
    // server timestamp (see VisitorInvitation.toMap doc).
    final data = invitation.toMap()
      ..['createdAt'] = FieldValue.serverTimestamp();

    await _ref.doc(token).set(data);
    return invitation;
  }

  // ═══════════════════════════════════════════════════════════════
  // READ
  // ═══════════════════════════════════════════════════════════════

  /// Live list of the calling resident's own passes, newest first.
  ///
  /// COMPOSITE INDEX: where('residentId') + orderBy('createdAt', desc) requires
  /// a (residentId ASC, createdAt DESC) index, declared in
  /// firestore.indexes.json. The status state machine means cancelled / expired
  /// rows remain visible (greyed in the UI) — a resident sees the full history
  /// of passes they issued.
  Stream<List<VisitorInvitation>> watchMyInvitations(String residentId) {
    return _ref
        .where('residentId', isEqualTo: residentId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map(
          (snap) => snap.docs
              .map((d) => VisitorInvitation.fromMap(d.id, d.data()))
              .toList(),
        );
  }

  /// Looks up one scanned visitor pass by its QR payload. Gate/admin users can
  /// read any pass by token; residents can only read their own passes per rules.
  Future<VisitorInvitation> getInvitationByQrPayload(String payload) async {
    return getInvitationByToken(tokenFromQrPayload(payload));
  }

  Future<VisitorInvitation> getInvitationByToken(String token) async {
    final snap = await _ref.doc(token).get();
    if (!snap.exists || snap.data() == null) {
      throw const VisitorRepositoryException('Visitor pass not found.');
    }
    return VisitorInvitation.fromMap(snap.id, snap.data()!);
  }

  // ═══════════════════════════════════════════════════════════════
  // UPDATE — narrow lifecycle transitions with immutable audit metadata
  // ═══════════════════════════════════════════════════════════════

  /// The issuing resident revokes an active pass before it is used
  /// (active → cancelled). A transaction re-reads the doc so a racing check-in
  /// can't slip between read and write.
  ///
  /// Ownership and the active-state precondition are re-checked here (defence
  /// in depth) AND enforced by the rule, which additionally requires that ONLY
  /// `status` changes (no other field may ride along — CWE-915).
  Future<void> cancelInvitation({
    required String token,
    required String residentId,
  }) async {
    final docRef = _ref.doc(token);
    await _firestore.runTransaction((tx) async {
      final snap = await tx.get(docRef);
      if (!snap.exists) {
        throw const VisitorRepositoryException('Visitor pass not found.');
      }
      final data = snap.data()!;
      if (data['residentId'] != residentId) {
        throw const VisitorRepositoryException(
          'You can only cancel your own visitor passes.',
        );
      }
      if (data['status'] != VisitorPassStatus.active.asString) {
        throw const VisitorRepositoryException(
          'Only an active pass can be cancelled.',
        );
      }
      // The rule restricts this transition to status plus cancellation audit.
      tx.update(docRef, {
        'status': VisitorPassStatus.cancelled.asString,
        'cancelledAt': FieldValue.serverTimestamp(),
        'cancelledBy': residentId,
      });
    });
  }

  /// Gate/admin transition: active -> checkedIn. Expired, cancelled, and
  /// already-used passes are rejected before Firestore; rules enforce the same
  /// lifecycle transition and audit metadata server-side.
  Future<void> checkInInvitation({
    required String token,
    required String staffId,
  }) async {
    if (staffId.trim().isEmpty) {
      throw const VisitorRepositoryException('Gate staff identity is missing.');
    }
    final docRef = _ref.doc(token);
    await _firestore.runTransaction((tx) async {
      final snap = await tx.get(docRef);
      if (!snap.exists) {
        throw const VisitorRepositoryException('Visitor pass not found.');
      }
      final invitation = VisitorInvitation.fromMap(snap.id, snap.data()!);
      if (!invitation.isCurrentlyValid) {
        throw const VisitorRepositoryException(
          'This visitor pass is not valid for entry.',
        );
      }
      tx.update(docRef, {
        'status': VisitorPassStatus.checkedIn.asString,
        'checkedInAt': FieldValue.serverTimestamp(),
        'checkedInBy': staffId,
      });
    });
  }

  /// Gate/admin transition: checkedIn -> checkedOut.
  Future<void> checkOutInvitation({
    required String token,
    required String staffId,
  }) async {
    if (staffId.trim().isEmpty) {
      throw const VisitorRepositoryException('Gate staff identity is missing.');
    }
    final docRef = _ref.doc(token);
    await _firestore.runTransaction((tx) async {
      final snap = await tx.get(docRef);
      if (!snap.exists) {
        throw const VisitorRepositoryException('Visitor pass not found.');
      }
      final data = snap.data()!;
      if (data['status'] != VisitorPassStatus.checkedIn.asString) {
        throw const VisitorRepositoryException(
          'Only a checked-in pass can be checked out.',
        );
      }
      tx.update(docRef, {
        'status': VisitorPassStatus.checkedOut.asString,
        'checkedOutAt': FieldValue.serverTimestamp(),
        'checkedOutBy': staffId,
      });
    });
  }
}
