// QR carries an opaque capability token only (no PII).
// Avoids CWE-200/CWE-359 (data exposure) and OWASP Mobile M6/M9.
// Token unguessability addresses CWE-330/CWE-338 via a CSPRNG.

import 'package:cloud_firestore/cloud_firestore.dart';

/// Lifecycle state of a single visitor pass.
///
/// THREAT MODEL NOTE:
/// - This state machine is the primary defence against pass replay
///   (CWE-294). A pass is honoured ONLY while [active]; [checkedIn] blocks a
///   second entry on the same token, and every terminal state
///   ([checkedOut], [expired], [cancelled]) is non-reusable.
/// - Persisted via [VisitorPassStatusX.asString] and re-read via
///   [VisitorPassStatusX.fromString], which FAILS CLOSED so a corrupted or
///   tampered value can only ever deny access, never grant it.
enum VisitorPassStatus {
  /// Issued and not yet used. The only state in which a pass is valid.
  active,

  /// Visitor has been admitted by a guard. Blocks re-entry on the token.
  checkedIn,

  /// Visit complete. Terminal.
  checkedOut,

  /// Past [VisitorInvitation.expiresAt] or otherwise timed out. Terminal.
  expired,

  /// Revoked by the resident before use. Terminal.
  cancelled,
}

extension VisitorPassStatusX on VisitorPassStatus {
  /// Canonical Firestore representation (the enum `name`). Using a stable
  /// string key decouples the stored value from enum declaration order.
  String get asString => name;

  /// Reconstructs a [VisitorPassStatus] from its persisted string.
  ///
  /// FAIL CLOSED: any unrecognised, missing, or tampered value resolves to
  /// [VisitorPassStatus.expired] — never to a state in which a pass could
  /// read as valid. A corrupted status field can therefore only ever *deny*
  /// access, never grant it (defence in depth around CWE-294).
  static VisitorPassStatus fromString(String value) {
    return VisitorPassStatus.values.firstWhere(
      (status) => status.name == value,
      orElse: () => VisitorPassStatus.expired,
    );
  }
}

/// An invitation for a visitor, stored as a single Firestore document.
///
/// SECURITY MODEL:
/// - [invitationId] IS the capability token AND the Firestore document ID.
///   There is deliberately NO separate `qrToken` field: the guard scanner
///   resolves a scanned token with one keyed `get()`, so no list/query
///   permission is ever required (hardens against CWE-639 enumeration).
/// - The QR code carries only [qrPayload] — a namespaced wrapper around the
///   opaque token — and never any visitor PII (CWE-200/CWE-359).
/// - The model is structurally immutable: every field is `final`, the
///   constructor is `const`, and [copyWith] exposes ONLY the two fields that
///   legitimately change over a pass's life ([invitationId] on first save,
///   [status] on each transition). There is no API on this object to mutate
///   visitor identity, unit, schedule, or validity window after creation.
class VisitorInvitation {
  /// The secure capability token, equal to the Firestore document ID.
  ///
  /// `null` before the document is persisted; populated via [copyWith] with
  /// the server-assigned ID immediately after the first write. The token is
  /// generated by a CSPRNG in Step 2 (CWE-330/CWE-338).
  final String? invitationId;

  /// UID of the resident who issued the invitation (the `/users/{uid}` doc).
  final String residentId;

  /// The resident's VERIFIED unit at issue time. Scopes the pass to a unit.
  final String unitNumber;

  final String visitorName;
  final String visitorContact;
  final int guestCount;

  /// Optional vehicle registration, if the visitor is driving in.
  final String? vehiclePlate;

  /// The calendar day the visit is expected.
  final DateTime visitDate;

  /// Human-entered expected time of arrival (free text, e.g. "2:30 PM").
  final String eta;

  final VisitorPassStatus status;

  final DateTime createdAt;

  /// Hard expiry. After this instant the pass is invalid regardless of the
  /// stored [status]; see [isCurrentlyValid].
  final DateTime expiresAt;

  /// Immutable audit metadata written during lifecycle transitions.
  final DateTime? cancelledAt;
  final String? cancelledBy;
  final DateTime? checkedInAt;
  final String? checkedInBy;
  final DateTime? checkedOutAt;
  final String? checkedOutBy;

  const VisitorInvitation({
    required this.invitationId,
    required this.residentId,
    required this.unitNumber,
    required this.visitorName,
    required this.visitorContact,
    this.guestCount = 1,
    this.vehiclePlate,
    required this.visitDate,
    required this.eta,
    required this.status,
    required this.createdAt,
    required this.expiresAt,
    this.cancelledAt,
    this.cancelledBy,
    this.checkedInAt,
    this.checkedInBy,
    this.checkedOutAt,
    this.checkedOutBy,
  });

  /// Start of the scheduled visit day in the device's local timezone.
  DateTime get validFrom =>
      DateTime(visitDate.year, visitDate.month, visitDate.day);

  bool get isUpcoming =>
      status == VisitorPassStatus.active && DateTime.now().isBefore(validFrom);

  bool get isExpired =>
      status == VisitorPassStatus.active && !DateTime.now().isBefore(expiresAt);

  /// The exact payload encoded into the QR code.
  ///
  /// Namespaced so the scanner can reject foreign QR codes before performing
  /// any lookup, and so the token is never mistaken for a bare URL/deeplink.
  /// Contains the opaque token ONLY — no visitor PII, ever.
  String get qrPayload => 'srm-visitor:$invitationId';

  /// True ONLY while the pass is both [VisitorPassStatus.active] AND within
  /// its validity window. This is the single source of truth the UI should
  /// consult: it fails closed once [expiresAt] passes even if the stored
  /// status has not yet been swept to [VisitorPassStatus.expired].
  bool get isCurrentlyValid {
    final now = DateTime.now();
    return status == VisitorPassStatus.active &&
        !now.isBefore(validFrom) &&
        now.isBefore(expiresAt);
  }

  /// Serialises to a Firestore map. DateTimes become [Timestamp]s.
  ///
  /// The document ID ([invitationId]) is deliberately NOT included: it is the
  /// document key, not a field, so the token is never duplicated inside the
  /// payload.
  ///
  /// NOTE: [VisitorRepository.createInvitation] OVERRIDES the `createdAt` entry
  /// of this map with [FieldValue.serverTimestamp] so the issue time is
  /// server-authoritative (never the forgeable client clock) — mirroring the
  /// announcements module. The [createdAt] value carried by this object is only
  /// a pre-write placeholder.
  Map<String, dynamic> toMap() {
    return {
      'residentId': residentId,
      'unitNumber': unitNumber,
      'visitorName': visitorName,
      'visitorContact': visitorContact,
      'guestCount': guestCount,
      'vehiclePlate': vehiclePlate,
      'visitDate': Timestamp.fromDate(visitDate),
      'eta': eta,
      'status': status.asString,
      'createdAt': Timestamp.fromDate(createdAt),
      'expiresAt': Timestamp.fromDate(expiresAt),
      'cancelledAt': cancelledAt == null
          ? null
          : Timestamp.fromDate(cancelledAt!),
      'cancelledBy': cancelledBy,
      'checkedInAt': checkedInAt == null
          ? null
          : Timestamp.fromDate(checkedInAt!),
      'checkedInBy': checkedInBy,
      'checkedOutAt': checkedOutAt == null
          ? null
          : Timestamp.fromDate(checkedOutAt!),
      'checkedOutBy': checkedOutBy,
    };
  }

  /// Rebuilds an invitation from its document ID and stored fields.
  ///
  /// [id] is the Firestore document ID — i.e. the capability token — and
  /// becomes [invitationId]. The status is parsed through the fail-closed
  /// [VisitorPassStatusX.fromString], so a missing or tampered status can
  /// only yield [VisitorPassStatus.expired], never a usable pass.
  factory VisitorInvitation.fromMap(String id, Map<String, dynamic> data) {
    return VisitorInvitation(
      invitationId: id,
      residentId: data['residentId'] as String,
      unitNumber: data['unitNumber'] as String,
      visitorName: data['visitorName'] as String,
      visitorContact: data['visitorContact'] as String,
      guestCount: data['guestCount'] as int? ?? 1,
      vehiclePlate: data['vehiclePlate'] as String?,
      visitDate: (data['visitDate'] as Timestamp).toDate(),
      eta: data['eta'] as String,
      status: VisitorPassStatusX.fromString((data['status'] as String?) ?? ''),
      // createdAt is written as FieldValue.serverTimestamp(); during Firestore's
      // latency-compensation / pending-write window the author's OWN local
      // snapshot momentarily sees it as null before the server value resolves.
      // Tolerate that transient null (→ DateTime.now()) rather than throw — the
      // fallback is never persisted and reconciles on the next snapshot. Mirrors
      // Announcement.fromFirestore's postedAt handling. visitDate / expiresAt
      // stay strict: they are always client-set and present.
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      expiresAt: (data['expiresAt'] as Timestamp).toDate(),
      cancelledAt: (data['cancelledAt'] as Timestamp?)?.toDate(),
      cancelledBy: data['cancelledBy'] as String?,
      checkedInAt: (data['checkedInAt'] as Timestamp?)?.toDate(),
      checkedInBy: data['checkedInBy'] as String?,
      checkedOutAt: (data['checkedOutAt'] as Timestamp?)?.toDate(),
      checkedOutBy: data['checkedOutBy'] as String?,
    );
  }

  /// Narrow copy. ONLY [invitationId] (set once on first save) and [status]
  /// (advanced by the pass state machine) may change; every other field is
  /// structurally immutable — there is intentionally no parameter to alter
  /// visitor identity, unit, schedule, or expiry after creation.
  VisitorInvitation copyWith({
    String? invitationId,
    VisitorPassStatus? status,
  }) {
    return VisitorInvitation(
      invitationId: invitationId ?? this.invitationId,
      residentId: residentId,
      unitNumber: unitNumber,
      visitorName: visitorName,
      visitorContact: visitorContact,
      guestCount: guestCount,
      vehiclePlate: vehiclePlate,
      visitDate: visitDate,
      eta: eta,
      status: status ?? this.status,
      createdAt: createdAt,
      expiresAt: expiresAt,
      cancelledAt: cancelledAt,
      cancelledBy: cancelledBy,
      checkedInAt: checkedInAt,
      checkedInBy: checkedInBy,
      checkedOutAt: checkedOutAt,
      checkedOutBy: checkedOutBy,
    );
  }

  /// Intentionally omits visitor PII (name, contact, plate) so it cannot leak
  /// into logs or crash reports (CWE-532).
  @override
  String toString() =>
      'VisitorInvitation(invitationId: $invitationId, '
      'unitNumber: $unitNumber, status: ${status.name}, '
      'expiresAt: $expiresAt)';
}
